### ISSUE TITLE
add config option(s) for which extra literals to identify

### ISSUE THREAD

**Issue by getify** [getify/literalizer#14]
Literalizer was initially intended _just_ to identify the complex literals (comments, strings, regexes, and back-ticks).

I added number-literal detection recently since the regex pattern for that is rather complex and you do have to look at the preceding context to make sure it's not part of an identifier (also a complex pattern).

Now I'm thinking while we're at it, why not go ahead and identify the simple literals `null`  `undefined`  `true`  `false`  `Infinity` and `NaN`?

**Side Note:** JS lexes `Infinity` and `NaN` as "Identifiers" and then later treats them as numbers during execution. This seems strange to me, like they should have just been lexed as number-literals. But I decided not to diverge from the way JS lexes. Same goes for not including the `-` in the number literal like with `-42`. JS doesn't treat the `-` as part of the number, so neither do I (which turns out to be much simpler/more performant for literalizer!).

But then, I realize that identifying numbers and these other simple literals costs perf and may or may not be useful to someone using _literalizer_.

So, perhaps we should put in two config options, like:

``` js
LIT.opts.identify_numbers = true;
LIT.opts.identify_simple = true;
```

For performance reasons, we might default both to `false`, but let people opt into those extra literals if they want them.

I also considered identifying keywords (and even operators), but I don't think those should qualify as literals. But I'm open to suggestions on that.

Just want to keep in mind, the goal here is a heuristic lexer to identify whatever we can as fast as we can without needed to do full grammar parsing (which is much slower). So have to balance usefulness against keeping literalizer "fast". If it's as slow as normal full-grammar parser but does far less, there's little point to its existence (except of course its "relaxed" mode).

---

The internal complication basically boils down to compiling a different general-state regex depending on the state of these configs. I don't think any of the rest of the code would need to consult the opts.

It would just consult the opts at the beginning of `lex()`, compile the appropriate general-state regex pattern, and proceed as normal. This might provide an initial fixed-cost hit to warm-up, but I think it should allow the case where you don't need those other non-complex literals to run a bit faster if not bogging down the general-state regex pattern (especially on bigger, more complex files, like a jQuery).

**Comment by ljharb** [comment]
Please do default everything to false - "absence" and "false" should mean the same thing. If you want to invert the default behavior, I'd prefer using a new option with an inverted english name.

**Comment by getify** [comment]
That's an interesting perspective.

I didn't follow that in [let-er](/getify/let-er) with the `annotate` option, which defaults to `true`. It seemed strange(r) to call it `dontAnnotate` or `noAnnotate`, because when set to false, then it's a double-negative, which is often seen as a smell. `noAnnotate = false` ==> `annotate = true` and `noAnnotate = true` ==> `annotate = false`.

I assume you're referring to the my [proposed config option for HTML comments](/getify/literalizer/issues/19#issuecomment-23964264), which (for safety) I want to default to being turned on.

So, it could be called `html_comments = true`, as I would have normally done. If we invert, would it be `no_html_comments = false`? Seems like a double-negative just like above. That's kinda unfortunate.

Or it could be `only_traditional_js_comments = false`, which avoids the double-negative but it sorta makes the name a little indirect and not terribly clear as to what it means (imagine reading that in the docs and not even knowing about HTML-style comments, it might be a _wtf?_ moment).

**Comment by ljharb** [comment]
I totally recognize the issues there - but I think passing "false" for any option and having behavior change is really weird, so I'd rather come up with a better option name. What about "ignoreHTMLComments"?

**Comment by getify** [comment]
The problem with "ignoreHTMLComments" is that it's misleading. It implies that you are recognizing an HTML comment and ignoring it (that is, removing it from the stream), when what you're really doing is refusing to identify "<!--" as a special sequence of characters.

Imagine you find some XYZ parser out there, and it has an option called "IgnoreComments"... are you going to assume that it means "leave /\* */ and // alone as stand-alone operators" or are you going to assume it means "drop comments from the stream and only identify real stuff"?

**Comment by ljharb** [comment]
True. Naming is hard. I don't like "html_comments" either because that doesn't tell me what it's doing with them - is it only allowing them? restricting them? adding them? etc.

"ignoreHTMLCommentSyntax"? That says to me that it's ignoring the syntax, but not the contents?

**Comment by getify** [comment]
That might work. It's long. But at least it's not as misleading.

**Comment by getify** [comment]
I think I've settled on:

``` js
opts.overlook_html_comment_markers
```

...which defaults to `false` so that it recognizes and processes them, and `true` means "overlook" them. The subtle but I think important semantic difference is that "ignore" could have implied "recognize and discard", but "overlook" more implies "don't recognize" without the double-negative. :)

**Comment by ljharb** [comment]
Sounds great! I look forward to the implementation :-)

**Comment by getify** [comment]
landed just now, as planned.
