### ISSUE TITLE
false-negatives on regex identification, need better rules

### ISSUE THREAD

**Issue by getify** [getify/literalizer#7]
[ Taken from the great pseudo-code and descriptions here: https://github.com/mozilla/sweet.js/wiki/design#give-lookbehind-to-the-reader ]

Examples currently broken:

``` js
if (true) /foo/g;
while (true) /foo/g;
for (;;) /foo/g;
with (foo) /foo/g;
```

and

``` js
function(){} /foo/g;
() => {} /foo/g;
```

---

Update: there's more to fix than the above-linked algorithm suggests:

https://github.com/mozilla/sweet.js/issues/82#issuecomment-22076003

``` js
var a, b = 2, i 3;

{x=4}/b/i;             // `/` starts a regex literal
{x:4}/b/i;             // `/` starts a regex literal
{y:5}{x:4}/b/i;        // `/` starts a regex literal
return
{x:4}/b/i;             // because of ASI, `/` starts a regex literal
throw
{x:4}/b/i;             // because of ASI, `/` starts a regex literal

a={x:4}/b/i;           // `/` is a divide
foo({x:4}/b/i);        // `/` is a divide
a={y:{x:4}/b/i};       // `/` is a divide
return{x:4}/b/i;       // `/` is a divide
throw{x:4}/b/i;        // `/` is a divide
```

**Comment by ljharb** [comment]
When is `function(){} /foo/g;` not a syntax error?

**Comment by getify** [comment]
@ljharb whenever it's a function-expression instead of a function-declaration, the `/` means divide, not a regex. So, these are all divisions:

``` js
var a = function(){} /foo/g;

// OR

foo( function(){} /foo/g );

// OR

return function(){} /foo/g;
```

**Comment by getify** [comment]
@ljharb also, check out these problems yet to be addressed: https://github.com/mozilla/sweet.js/issues/82#issuecomment-22076003

**Comment by ljharb** [comment]
Ah, makes sense. Thanks. That is a tricky one.

**Comment by getify** [comment]
closing for now because I think it's vastly improved, and pretty near "correct".
